var output = {
  "Listening Level 1": "<p>Master the ability to understand:</p><ul><li>Simple Sentences</li><li>Basic Questions &ndash; Yes/No</li></ul><p>Improve your ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Specific Details</li><li>Requests</li><li>Simple Questions &ndash;&nbsp; Who/What/Where/When</li></ul>",

  "Listening Level 2": "<p>Master the ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Specific Details</li><li>Requests</li><li>Sequence of Events</li><li>Simple Questions &ndash;&nbsp; Who/What/Where/When</li></ul><p>Improve your ability to understand:</p><ul><li>Instructions</li><li>Preferences</li><li>Comparisons</li><li>Cause &amp; Effect</li><li>Agreement &amp; Disagreement</li><li>Fact &amp; Opinion</li><li>Simple Questions &ndash; Who/What/Where/When/Why/How</li></ul>",

  "Listening Level 3": "<p>Master the ability to understand:</p><ul><li>Instructions</li><li>Preferences</li><li>Comparisons</li><li>Cause &amp; Effect</li><li>Agreement &amp; Disagreement</li><li>Fact &amp; Opinion</li><li>Simple Questions &ndash; Who/What/Where/When/Why/How</li></ul><p>Improve your ability to understand:</p><ul><li>Inferences</li><li>Opinions</li><li>Comparisons &amp; Contrasts</li><li>Cause &amp; Effect</li><li>Basic Hypothetical Situations</li><li>Formal &amp; Informal</li></ul>",

  "Listening Level 4": "<p>Master the ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Specific Details</li><li>Opinions</li><li>Comparisons &amp; Contrasts</li><li>Cause &amp; Effect</li><li>Inferences</li><li>Basic Hypothetical Situations</li><li>Formal &amp; Informal Speech</li><li>Simple Questions &ndash; Who/What/Where/When/Why/How</li></ul>",

  "Reading Level 1": "<p>Master the ability to understand:</p><ul><li>Main Ideas</li><li>Specific Details</li><li>Basic Questions &ndash; Yes/No</li></ul><p>Improve your ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Requests</li><li>Opinions</li><li>Gist</li><li>Sequence of Events</li><li>Simple Questions &ndash;&nbsp; Who/What/Where/When</li></ul>",

  "Reading Level 2": "<p>Master the ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Requests</li><li>Opinions</li><li>Gist</li><li>Sequence of Events</li><li>Simple Questions &ndash;&nbsp; Who/What/Where/When</li></ul><p>Improve your ability to understand:</p><ul><li>Preferences</li><li>Comparison</li><li>Cause &amp; Effect</li><li>Inferences</li><li>Fact &amp; Opinion</li><li>Simple Questions &ndash; Who/What/Where/When/Why/How</li></ul>",

  "Reading Level 3": "<p>Master the ability to understand:</p><ul><li>Preferences</li><li>Comparison</li><li>Cause &amp; Effect</li><li>Inferences</li><li>Fact &amp; Opinion</li><li>Simple Questions &ndash; Who/What/Where/When/Why/How</li></ul><p>Improve your ability to understand:</p><ul><li>Comparisons &amp; Contrasts</li><li>Instructions</li><li>Inferences</li></ul>",

  "Reading Level 4": "<p>Master the ability to understand:</p><ul><li>Main Ideas</li><li>Supporting Ideas</li><li>Specific Details</li><li>Opinions</li><li>Cause &amp; Effect Relationships</li><li>Comparisons &amp; Contrasts</li><li>Instructions</li><li>Inferences</li><li>Author&rsquo;s Purpose</li><li>Difference between Formal &amp; and Informal Text</li></ul>",

  "Writing Level 1": "<p>Master the ability to:</p><ul><li>Make a List</li><li>Respond to an Invitation</li><li>Respond to a Request</li><li>Express a Greeting</li><li>Express Likes and Dislikes</li><li>Describe a Location</li><li>Ask Basic Questions &ndash; Yes/No</li></ul><p>Improve your ability to:</p><ul><li>Create a Topic Sentence</li><li>Tell a Personal Experience</li><li>Extend an Invitation</li><li>Make a Plan</li><li>Express Requests &amp; Offers</li><li>Express Opinion</li><li>Describe a Sequence of Events</li><li>Create a Summary</li><li>Response to Questions &ndash; Who/When/Where</li></ul>",

  "Writing Level 2": "<p>Master the ability to:</p><ul><li>Create a Topic Sentence</li><li>Tell a Personal Experience</li><li>Extend an Invitation</li><li>Make a Plan</li><li>Express Requests &amp; Offers</li><li>Express Opinion</li><li>Describe a Sequence of Events</li><li>Create a Summary</li><li>Respond to Questions &ndash; Who/When/Where</li></ul><p>Improve your ability to:</p><ul><li>Create Simple Sentences</li><li>Create Simple Paragraphs</li><li>Express Preferences &amp; Opinions</li><li>Describe Cause &amp; Effect Relationships</li><li>Express Agreement &amp; Disagreement</li><li>Make Comparisons</li><li>Describe a Sequence of Steps</li><li>Create a Summary &amp; Reports</li><li>Ask &amp; Repond to Questions Using Complex Sentence Structures</li></ul>",

  "Writing Level 3": "<p>Master the ability to write the following:</p><ul><li>Create Simple Sentences</li><li>Create Simple Paragraphs</li><li>Express Preferences &amp; Opinions</li><li>Describe Cause &amp; Effect Relationships</li><li>Express Agreement &amp; Disagreement</li><li>Make Comparisons</li><li>Describe a Sequence of Steps</li><li>Create a Summary &amp; Reports</li><li>Ask &amp; Repond to Questions Using Complex Sentence Structures</li></ul><p>Improve your ability to:</p><ul><li>Create a Simple Essay<ul><li>Introductory Paragraph</li><li>Main Ideas &amp; Supporting Ideas</li></ul></li><li>Tell a Story</li><li>Describe People, Places, Objects, and Events</li><li>Express &amp; Support Opinion</li><li>Compare &amp; Contrast People, Places, Objects, and Events</li><li>Summarize &amp; Report</li><li>Paraphrase</li><li>Use Informal &amp; Formal Text</li></ul>",

  "Writing Level 4": "<p>Master the ability to:</p><ul><li>Create a Simple Essay<ul><li>Introductory Paragraph</li><li>Main Ideas &amp; Supporting Ideas</li></ul></li><li>Tell a Story</li><li>Describe People, Places, Objects, and Events</li><li>Express &amp; Support Opinion</li><li>Compare &amp; Contrast People, Places, Objects, and Events</li><li>Summarize &amp; Report</li><li>Paraphrase</li><li>Use Informal &amp; Formal Text</li></ul>",

  "Speaking Level 1": "<p>Master the ability to:</p><ul><li>Make an Appointment</li><li>Greet Someone</li><li>Get to Know Someone</li><li>Make Simple Requests</li><li>Use Simple Commands</li><li>Express Likes &amp; Dislikes</li><li>Describe a Location</li><li>Ask &amp; Answer Questions &ndash; Yes/No/What</li></ul><p>Improve your ability to:</p><ul><li>Express &amp; Support Ideas</li><li>Tell a Story</li><li>Extend an Invitation</li><li>Coordinate Simple Plans</li><li>Make Basic Requests &amp; Offers</li><li>Express &amp; Support Opinions</li><li>Describe a Sequence of Events</li><li>Give a Simple Summary</li><li>Ask &amp; Answer Questions &ndash; Who/What/When/Where/Yes/No</li></ul>",

  "Speaking Level 2": "<p>Master the ability to:</p><ul><li>Express &amp; Support Ideas</li><li>Tell a Story</li><li>Extend an Invitation</li><li>Coordinate Simple Plans</li><li>Make Basic Requests &amp; Offers</li><li>Express &amp; Support Opinions</li><li>Describe a Sequence of Events</li><li>Give a Simple Summary</li><li>Ask &amp; Answer Questions &ndash; Who/What/When/Where/Yes/No</li></ul><p>Improve your ability to:</p><ul><li>Give a Simple Presentation<ul><li>Introduction with Main Idea</li><li>Supporting Ideas</li></ul></li><li>Tell a Story</li><li>Express Preferences</li><li>Express &amp; Support Opinion</li><li>Explain Cause &amp; Effect</li><li>Express Agreement and Disagreement</li><li>Make Simple Comparisons</li><li>Give Step-by-Step Instructions</li><li>Give a Simple Summary</li><li>Ask &amp; Answer Questions &ndash; Who/What/When/Where/Why/How</li></ul>",

  "Speaking Level 3": "<p>Master the ability to:</p><ul><li>Give a Simple Presentation</li><li>Tell a Story</li><li>Express Preferences</li><li>Express &amp; Support Opinion</li><li>Explain Cause &amp; Effect</li><li>Express Agreement and Disagreement</li><li>Make Simple Comparisons</li><li>Give Step-by-Step Instructions</li><li>Give a Simple Summary</li><li>Ask &amp; Answer Questions &ndash; Who/What/When/Where/Why/How</li></ul><p>Improve your ability to:</p><ul><li>Give a Presentation</li><li>Narrate</li><li>Describe Objects, People, Places, and Events</li><li>Express &amp; Support Opinion</li><li>Compare &amp; Contrast Information</li><li>Give Step-by-Step Instructions</li><li>Summarize Information</li><li>Paraphrase Simple Ideas</li><li>Discuss Hypothetical Situations</li><li>Use Formal &amp; Informal Speech</li><li>Respond Correctly to Unexpected Situations</li></ul>",

  "Speaking Level 4": "<p>Master the ability to:</p><ul><li>Give a Presentation</li><li>Narrate</li><li>Describe Objects, People, Places, and Events</li><li>Express &amp; Support Opinion</li><li>Compare &amp; Contrast Information</li><li>Give Step-by-Step Instructions</li><li>Summarize Information</li><li>Paraphrase Simple Ideas</li><li>Discuss Hypothetical Situations</li><li>Use Formal &amp; Informal Speech</li><li>Respond Correctly to Unexpected Situations</li></ul>"
}

module.exports = output;
